- name: Minio Setup | Fail fast if variables are not set
  ansible.builtin.fail:
    msg: "You need to specifcy the path to certificate and key to use"
  when:
    - minio_configure_ssl
    - minio_generate_certs
    - minio_cert_path is not defined or minio_cert_path == ""
    - minio_key_path is not defined or minio_key_path == ""

- name: Minio Setup | Ensure Minio container is not present already
  containers.podman.podman_container:
    name: minio
    state: absent

- name: Minio Setup | Ensure podman network is not present
  containers.podman.podman_network:
    name: minio
    state: absent

- name: Minio Setup | Configure podman network
  containers.podman.podman_network:
    name: minio
    disable_dns: false
    internal: false
    recreate: false
    state: present

- name: Minio Setup | Ensure podman volume is not present
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - minio-data

- name: Minio Setup | Configure podman volume
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: present
  loop:
    - minio-data

- name: Minio Setup | Create certs directory
  ansible.builtin.file:
    state: directory
    path: ./certs
    mode: "0755"

- name: Minio Setup | Generate and configure certs for https
  when:
    - minio_configure_ssl
    - minio_generate_certs
  block:
    - name: Minio Setup | Generate private key for SSL certificate
      community.crypto.openssl_privatekey:
        path: ./certs/private.key

    - name: Minio Setup | Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: ./certs/public.crt
        privatekey_path: ./certs/private.key
        provider: selfsigned

- name: Minio Setup | Configure certs for https
  when:
    - minio_configure_ssl
    - not minio_generate_certs
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: ./certs/{{ item.dest }}
    mode: "0755"
  loop:
    - source: "{{ minio_cert_path }}"
      dest: public.crt
    - source: "{{ minio_key_path }}"
      dest: private.key

- name: Minio Setup | Create minio container
  containers.podman.podman_container:
    name: minio
    network:
      - minio
    volume:
      - minio-data:/bitnami/minio/data
      - "{{ './certs:/certs:Z' if minio_configure_ssl else omit }}"
    image: docker.io/bitnami/minio
    ports:
      - "{{ minio_api_port | default(9000, true) }}:{{ minio_api_port | default(9000, true) }}"
      - "{{ minio_console_port | default(9001, true) }}:{{ minio_console_port | default(9001, true) }}"
    env:
      MINIO_ROOT_USER: "{{ minio_root_user | default('minio-admin', true) }}"
      MINIO_ROOT_PASSWORD: "{{ minio_root_password | default('minio-pwd', true) }}"
      MINIO_API_PORT_NUMBER: "{{ minio_api_port | default(9000, true) }}"
      MINIO_CONSOLE_PORT_NUMBER: "{{ minio_console_port | default(9001) }}"
      MINIO_SERVER_HOST: "{{ minio_server_host | default(ansible_fqdn, true) }}"
      MINIO_DEFAULT_BUCKETS: "{{ minio_default_buckets | default('', true) }}"
      MINIO_SCHEME: "{{ 'https' if minio_configure_ssl else 'http' }}"
