- name: Minio Setup | Configure podman network
  containers.podman.podman_network:
    name: minio
    disable_dns: false
    internal: false
    recreate: false
    state: present

- name: Minio Setup | Configure podman volume
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: present
  loop:
    - minio-data

# - name: Minio Setup | Ensure Minio container is not present already
#   containers.podman.podman_container:
#     name: minio
#     state: absent

- name: Minio Setup | Create certs directory
  ansible.builtin.file:
    state: directory
    path: ./certs
    mode: 0755

- name: Minio Setup | Configure certs for https
  when: minio_configure_ssl
  block:
    - name: Minio Setup | Generate private key for SSL certificate
      community.crypto.openssl_privatekey:
        path: ./certs/private.key

    - name: Minio Setup | Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: ./certs/public.crt
        privatekey_path: ./certs/private.key
        provider: selfsigned

- name: Minio Setup | Create minio container
  containers.podman.podman_container:
    name: minio
    network:
      - minio
    volume:
      - minio-data:/data
      - "{{ './certs:/root/.minio/certs:Z' if minio_configure_ssl else omit }}"
    image: quay.io/minio/minio
    command: 'server /data --console-address :9090'
    ports:
      - "{{ minio_api_port | default(9000,true) }}:9000"
      - "{{ minio_console_port | default(9090,true) }}:9090"
    env:
      MINIO_ROOT_USER: "{{ minio_root_user | default('minio-admin', true) }}"
      MINIO_ROOT_PASSWORD: "{{ minio_root_password | default('minio-pwd', true) }}"
      MINIO_SCHEME: "{{ 'https' if minio_configure_ssl | default('http', true) }}"